#!/usr/bin/env python

# MIT License

# Copyright (c) 2015, 2017 Marie Lemoine-Busserolle

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import sys
import nifty

# TODO(nat): have a syntax of runNifty <script name> <inputfile>.

if __name__ == '__main__':

    if '--version' in sys.argv:
        sys.stdout.write("%s\n" % stpipe.__version__)
        sys.exit(0)

    # TODO(nat): find a better way to do this.
    if 'nifsPipeline' in sys.argv[1]:
        nifty.nifsPipeline.start(sys.argv[2:])
    if 'nifsLowMemoryPipeline' in sys.argv[1]:
        nifty.nifsLowMemoryPipeline.start(sys.argv[2:])
    if 'nifsSort' in sys.argv[1]:
        nifty.nifsSort.start()
    if 'nifsBaselineCalibration' in sys.argv[1]:
        nifty.nifsBaselineCalibration.start()
    if 'nifsReduce' in sys.argv[1]:
        if 'Telluric' in sys.argv[2]:
            nifty.nifsReduce.start('Telluric')
        elif 'Science' in sys.argv[2]:
            nifty.nifsReduce.start('Science')
    """elif 'nifsSort' in sys.argv:
        nifty.nifsSort.start()                            # TODO(nat): make these able parse input on their own.
    elif 'nifsBaselineCalibration' in sys.argv:           # Right now they assume config is in ./config.cfg...
        nifty.nifsBaselineCalibration.start()
    elif 'nifsReduce' in sys.argv:
        nifty.nifsReduce.start()"""
